<?php
/**
 * @file
 * Code for the GSB Feature CTA feature.
 */

include_once 'gsb_feature_cta.features.inc';


/**
 * Implements hook_entity_info_alter().
 */

function gsb_feature_cta_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['cta'] = array(
    'label' => t('CTA'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_content_list.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 10,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/cta',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

// Formatter

/**
 * Implementation of hook_field_formatter_info().
 *
 * Here we tell Drupal about our custom field formatter -
 * 'gsb_slideshow_default_format'.
 *
 */
function gsb_feature_cta_field_formatter_info() {
    return array(
        'gsb_cta_default_format' => array(
            'label' => t('Field Collection CTA'),
            'field types' => array('field_collection'),
            'settings' => array('view_mode' => 'full'),
        ),
    );
}

/**
 * Implements hook_field_formatter_view().
 */
function gsb_feature_cta_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

    $element = array();

    $settings = $display['settings'];

    $style = $entity->field_cta_style['und'][0]['value'];
    if ($style == 'cta-red-gradient')
        $style_class = 'separated-box';
    else
        $style_class = 'designed-box';

    $element[0]['#markup'] = '';
    foreach ($items as $delta => $item_data) {
        if ($delta == 0)
            $element[0]['#markup'] = '<div class="cta-wrapper ' . $style_class . '">';
        if ($field_collection = entity_metadata_wrapper('field_collection_item', $item_data['value'])) {
            $element[0]['#markup'] .= '<a href="' . $field_collection->field_link_single->get('url')->value() . '" class="item-' . $delta . ' ' . $style . ' cta-link">';
            $element[0]['#markup'] .= '<span>' . $field_collection->field_cta_action->value() . '</span>';
            $element[0]['#markup'] .= '<b>' . $field_collection->field_link_single->get('title')->value() . '</b><i></i>';
            $element[0]['#markup'] .= '</a>';
        }
        if ($delta == count($items) - 1)
            $element[0]['#markup'] .= '</div>';
    }
    return $element;
}
