<?php
/**
 * @file
 * Code for the GSB Feature CTA feature.
 */

include_once 'gsb_feature_cta.features.inc';


/**
 * Implements hook_entity_info_alter().
 */

function gsb_feature_cta_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['gsb_cta'] = array(
    'label' => t('Add GSB CTA'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_content_list.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 10,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/gsb-cta',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
